#!/bin/sh

# Prep for a build.
prep() {
    autoreconf --install
}

clean() {
    if [ ! -e ./MK -o "$0" != "./MK" ]; then
        echo "MK must be called from the directory it's located in" >&2
        exit 1
    fi
    rm -f aclocal.m4
    rm -rf autom4te.cache
    rm -f config.h
    rm -f config.h.in
    rm -f config.h.in~
    rm -f configure
    rm -f config.status
    rm -f config.guess
    rm -f config.sub
    rm -f stamp-h1
    rm -f config.log
    rm -f install-sh
    rm -f missing
    rm -f depcomp
    find . -name Makefile.in -exec rm -f {} \;
    find . -name Makefile -exec rm -f {} \;
}

if [ "x$1" = "xprep" ]; then
    prep
elif [ "x$1" = "xclean" ]; then
    clean
fi
